on: [push, pull_request]
name: Dummy-action
jobs:
  name: show-repo
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Show repo
      run: |
        ls -R
    - name: Show the content of all the files
      run: |
        find . -type f -not -path */\.* -exec echo '{}' ';' -exec cat '{}' ';'
